### ISSUE TITLE
class not found 问题

### ISSUE THREAD

**Issue by ftvbftvbq** [williamfzc/randunit#3]
问个问题，问这边运行程序报错，我把你安卓demo下文件都复制了一份过来，并且在主程序下的gradle下配置了：testImplementation "com.github.williamfzc.randunit:randunit-android:0.1.1"，在root项目下的gradle下配置了：maven { url 'https://jitpack.io' }，但是跑randjunit还是报错：class not found:
![image](https://user-images.githubusercontent.com/8132013/115538440-7718aa80-a2ce-11eb-9d07-0fe3102cb666.png)
![image](https://user-images.githubusercontent.com/8132013/115538483-81d33f80-a2ce-11eb-8f10-65fbc2d6c0bc.png)

**Comment by williamfzc** [comment]
这个 class not found 貌似不是 randunit 里的类找不到，是你的 junit class 找不到了；
这种情况下你随便建一个单测用例应该也是报一样的错，跟 IDE 配置有关；
建议是 随便建一个不带randunit的单测用例看看能否运行 先，能跑通之后再接入即可

**Comment by ftvbftvbq** [comment]
![image](https://user-images.githubusercontent.com/8132013/117415775-4467e680-af4b-11eb-883c-5e4ddd38d26f.png)
为什么结果是空的？需要什么其他配置？
