### ISSUE TITLE
No Test were found

### ISSUE THREAD

**Issue by ftvbftvbq** [williamfzc/randunit#7]

**Comment by williamfzc** [comment]
https://github.com/williamfzc/randunit/issues/6

reflections 在 android 上有问题，用类代替吧
可以选几个关键的类试试

**Comment by ftvbftvbq** [comment]
> #6
> 
> reflections 在 android 上有问题，用类代替吧
> 可以选几个关键的类试试

能给我个例子吗？谢谢！

**Comment by williamfzc** [comment]
#6  里不是有嘛：

```kotlin
RandUnit.collectStatements(setOf(
    YourService::class.java,
    AnotherService::class.java
), scanConfig)
```

**Comment by ftvbftvbq** [comment]
![image](https://user-images.githubusercontent.com/8132013/117930289-64731d80-b330-11eb-92e8-98f219813600.png)
单独指定了，但是还是没跑出任何结果，请问下，这对源代码有什么要求吗？谢谢！

**Comment by williamfzc** [comment]
看着都还在junit层，环境问题，google下吧

https://blog.csdn.net/weixin_43272781/article/details/111027076

qq 178894043
